apiVersion: v1
kind: Service
metadata:
  name: homie-ingest
  labels:
    app.kubernetes.io/name: homie-ingest
    app.kubernetes.io/part-of: homie
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: homie-ingest
  ports:
    - name: http
      port: 8080
      targetPort: http
